### ISSUE TITLE
Helep

### ISSUE THREAD

**Issue by MerlijnBusch** [BramTerlouw/Big-Data-AI-Minor-Group-1#1]
Traceback (most recent call last):
            File "C:\Users\merli\big-data-ai-minor\train.py", line 13, in <module>
              history = model.fit(train_images, train_labels,
            File "C:\Users\merli\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler   
              raise e.with_traceback(filtered_tb) from None
            File "C:\Users\merli\anaconda3\lib\site-packages\keras\engine\training.py", line 1576, in fit
              raise ValueError(
          ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)
          `, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `
          tf.keras`.

we get this error do you maybe know how to fix this? or where the error is its on the branch `feature/data-model
`

**Comment by MerlijnBusch** [comment]
update annotations files are missing
